namespace :app do
  name_of_app    = ""
  bucket_name    = ""
  awscli_profile = ""
  
  desc "Archive app for upload."
  task :archive do
    sh %{ zip -r #{name_of_app} * }
  end
  
  desc "Upload a local .zip file to an AWS S3 bucket."
  task :upload do
    sh %{ aws s3 cp #{name_of_app}.zip s3://#{bucket_name} --profile #{awscli_profile} }
  end
end